# Generated by Django 3.2.6 on 2021-09-01 18:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fileparse', '0002_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.RemoveField(
            model_name='uploadyaml',
            name='comfig',
        ),
        migrations.AddField(
            model_name='uploadyaml',
            name='configs',
            field=models.FileField(default=django.utils.timezone.now, upload_to='fileparse/'),
            preserve_default=False,
        ),
    ]
