# Generated by Django 3.2.6 on 2021-09-03 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileparse', '0004_auto_20210903_0328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadextras',
            old_name='extras',
            new_name='files',
        ),
    ]
